import { Department } from '../models/department';
import { Employee } from '../models/employee';
import { Title } from '../models/title';
/**
 * Initial data for departments.
 * This data is used to populate the department array when the service is first initialized.
 */
export const DEPARTMENTS: Department[] = [
  {
    id: 1,
    name: '1st Front Office',
    keywords: ['Banking'],
    notes: 'This office includes:\n - corporate finance\n - sales personnel',
    startDate: new Date('2020-01-20'),
    endDate: new Date('2020-02-14'),
  },
  {
    id: 2,
    name: '2nd Front Office',
    keywords: ['Insurance'],
    notes: 'This office includes:\n - corporate finance\n - sales personnel',
    startDate: new Date('2020-01-20'),
    endDate: new Date('2020-02-14'),
  },
  {
    id: 3,
    name: '1st Middle Office',
    keywords: ['Banking'],
    notes:
      'This office includes:\n - risk management\n - information technology',
    startDate: new Date('2020-01-20'),
    endDate: new Date('2020-02-14'),
  },
  {
    id: 4,
    name: '2nd Middle Office',
    keywords: ['Insurance'],
    notes:
      'This office includes:\n - risk management\n - information technology',
    startDate: new Date('2020-01-20'),
    endDate: new Date('2020-02-14'),
  },
  {
    id: 5,
    name: '1st Back Office',
    keywords: ['Banking'],
    notes:
      'This office includes:\n - administrative services\n - support services',
    startDate: new Date('2020-01-20'),
    endDate: new Date('2020-02-14'),
  },
  {
    id: 6,
    name: '2nd Back Office',
    keywords: ['Insurance'],
    notes:
      'This office includes:\n - administrative services\n - support services',
    startDate: new Date('2020-01-20'),
    endDate: new Date('2020-02-14'),
  },
];
/**
 * Initial employee data for the application.
 * This data is used to populate the employee array when the application starts.
 */
export const EMPLOYEES: Employee[][] = [
  [
    {
      id: 1,
      firstName: 'John',
      lastName: 'Doe',
      title: Title.Manager,
      phone: '012345678',
      mail: 'user@example.com',
      streetName: 'Massachusetts Ave NW',
      houseNumber: '2101',
      postalCode: '20008',
      locality: 'Washington',
      province: 'DC',
      country: 'United States',
    },
    {
      id: 2,
      firstName: 'Brett',
      lastName: 'Boe',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
      streetName: 'Fleet St',
      houseNumber: '175',
      postalCode: 'EC4A 2EA',
      locality: 'London',
      province: '',
      country: 'United Kingdom',
    },
    {
      id: 3,
      firstName: 'Carla',
      lastName: 'Coe',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
      streetName: 'Av. de José Antonio',
      houseNumber: '38',
      postalCode: '28013',
      locality: 'Madrid',
      province: '',
      country: 'Spain',
    },
    {
      id: 4,
      firstName: 'Donna',
      lastName: 'Doe',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
      streetName: 'Rue Saint-Antoine',
      houseNumber: '1',
      postalCode: '75004',
      locality: 'Paris',
      province: '',
      country: 'France',
    },
    {
      id: 5,
      firstName: 'Kriste',
      lastName: 'Etue',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
      streetName: 'Unter den Linden',
      houseNumber: '7',
      postalCode: '10117',
      locality: ' Berlin',
      province: '',
      country: 'Germany',
    },
  ],
  [
    {
      id: 6,
      firstName: 'Frank',
      lastName: 'Foe',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 7,
      firstName: 'Grace',
      lastName: 'Goe',
      title: Title.Manager,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 8,
      firstName: 'Harry',
      lastName: 'Hoe',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 9,
      firstName: 'Larry',
      lastName: 'Loe',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 10,
      firstName: 'Mark',
      lastName: 'Moe',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
  ],
  [
    {
      id: 11,
      firstName: 'Norma',
      lastName: 'Noe',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 12,
      firstName: 'Paula',
      lastName: 'Poe',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 13,
      firstName: 'Richard',
      lastName: 'Roe',
      title: Title.Manager,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 14,
      firstName: 'Sammy',
      lastName: 'Soe',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 15,
      firstName: 'Tommy',
      lastName: 'Toe',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
    },
  ],
  [
    {
      id: 16,
      firstName: 'Vince',
      lastName: 'Voe',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 17,
      firstName: 'William',
      lastName: 'Woe',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 18,
      firstName: 'Xerxes',
      lastName: 'Xoe',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 19,
      firstName: 'Richard',
      lastName: 'Miles',
      title: Title.Manager,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 20,
      firstName: 'John',
      lastName: 'Stiles',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
    },
  ],
  [
    {
      id: 21,
      firstName: 'John',
      lastName: 'Noakes',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 22,
      firstName: 'Mary',
      lastName: 'Major',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 23,
      firstName: 'Jane',
      lastName: 'Smith',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 24,
      firstName: 'John',
      lastName: 'Bloggs',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 25,
      firstName: 'Roger',
      lastName: 'Galvin',
      title: Title.Manager,
      phone: '012345678',
      mail: 'user@example.com',
    },
  ],
  [
    {
      id: 26,
      firstName: 'Rick',
      lastName: 'Snyder',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 27,
      firstName: 'Bill',
      lastName: 'Schuette',
      title: Title.Analyst,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 28,
      firstName: 'William',
      lastName: 'Forsyth',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 29,
      firstName: 'Wilbur',
      lastName: 'Friedman',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
    {
      id: 30,
      firstName: 'Thomas',
      lastName: 'Ferguson',
      title: Title.Developer,
      phone: '012345678',
      mail: 'user@example.com',
    },
  ],
];
